# AP 155 Lab Exercise
---
## Exercise 5: Matrices

_Instructions_: 
- **Report figure:** No report figure. Points in the report figure will be allocated to the report discussion 
- **Report discussion:**
  - What were the basis linear equations used to set up the matrix in each question of Problem 2?
  - Once you set up the matrices, what function did you use to solve the matrix equation (Could have different answers)? Check the docstring/documentation/other references and summarize the mechanism behind the function 
- **Code**: Complete the code and ensure it is functional, error-free, readable, and efficient (where needed). Include concise Markdown documentation highlighting the critical steps of your algorithm for each problem.

### Student Information
- _Full Name_: Castaneda, Joaquin
- _Student No._: 2024-09743
- _Section_: THR-TX-1

### Grading Information (c/o Lab Instructor)
- [Rubrics description link](https://drive.google.com/file/d/1BMSlPot2Mc7XLu0eo4S8I8gLBsIadbCL/view?usp=sharing) (Note: percentages may still be tweaked)

| Criteria | Score | Subtotal |
| --- | --- | --- |
| Report figure | XX | 20 |
| Report discussion | XX | 20|
| Code readability | XX | 20 |
| Code efficiency | XX | 20 | 
| Code appropriateness  | XX | 20 | 
| **TOTAL** | XXX | 100 |

_Date and Time Scored (MM/DD/YYYY HH:MM AM/PM):_:_

---
## Section 1: Report

### Report discussion

**1.** For Problem 2, the basis linear equations came from setting the net force on the hanging mass to be equal to zero (for both horizontal and vertical directions). Since the mass is static (stationary), the forces acting on it must be balanced.

So, for the horizontal direction,

$$
\sum F_x = 0
$$

which gives

$$
T_1\cos\alpha - T_2\cos\beta = 0.
$$

And for the vertical direction,

$$
\sum F_y = 0
$$

which gives us

$$
T_1\sin\alpha + T_2\sin\beta - Mg = 0.
$$

Here, $T_1$ and $T_2$ are the tensions in the two ropes, whereas, $Mg$ is the weight of the mass that is hanging. The sin and cos terms are used to separate the tension forces into horizontal and vertical components. These two equations contain the two unknown tensions. In the code, these equations were rearranged and written in matrix form in order to allow `np.linalg.solve()` to calculate the values of $T_1$ and $T_2$.

<br>

**2.** The function I used to solve the matrix equation was `np.linalg.solve()`. This function is used to solve a system of linear equations written in the form $A\mathbf{x}=\mathbf{b}$, wherein $A$ is the coefficient matrix, $\mathbf{x}$ is the vector that contains the unknown variables, and $\mathbf{b}$ is the vector that contains the known values. It works by using numerical linear algebra methods to solve the equations simultaneously and find the values of $\mathbf{x}$. In Problem 2, the unknown vector contained the two rope tensions, $T_1$ and $T_2$. The coefficient matrix was formed from the sin and cos terms of the rope angles, whereas, the right-hand-side vector contained the known force values. Hence, using `np.linalg.solve()` allowed the two tensions to be calculated directly without manually solving the equations.


<br>

### Reflection
I wish I had already known this when taking 106, 107, and 116.


---
## Section 2: Code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

### Problem 1: (Circuit Analysis)


Consider a long chain of resistors wired up like this:

<img src="reschain.png" alt="Alt text" width=95%>

All the resistors have the same resistance~$R$.  The power rail at the top is at voltage~$V_+=5$V.  The problem is to find the voltages $V_1...V_N$ at the internal points in the circuit.

1. **Using Ohm's law and the Kirchhoff current law**, which says that the total net current flow out of (or into) any junction in a circuit must be zero, show that the voltages $V_1\ldots V_N$ satisfy the equations

$$3V_1 - V_2 - V_3 = V_+ $$

$$-V_1 + 4V_2 - V_3 - V_4 = V_+ $$
      
$$-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2} = 0 $$

$$-V_{N-3} - V_{N-2} + 4V_{N-1} - V_N = V_- = 0 $$
$$-V_{N-2} - V_{N-1} + 3V_N = V_- = 0 $$

Note: The assignment of $V_-$ is to make the equations symmetric

2. Express these equations in vector form~$A\vec{v} = \vec{w}$ and find the values of the matrix~$A$ and the vector~$\vec{w}$.

3. Write a program to solve for the values of the~$V_i$ when there are $N=6$ internal junctions with unknown voltages.  (Hint: All the values of $V_i$ should lie between zero and $5$V.  If they don't, something is wrong.)

4. Now repeat your calculation for the case where there are $N=10\,000$ internal junctions.  This part is not possible using standard tools like the *solve* function.  You need to make use of the fact that the matrix~$\vec{A}$ is banded.  

Using Ohm's law,

$$
I=\frac{V_a-V_b}{R}.
$$

So at each junction, we can use Kirchhoff's law, (so total current is zero).

For $V_1$,

$$
\frac{V_1-V_+}{R}
+\frac{V_1-V_2}{R}
+\frac{V_1-V_3}{R}=0.
$$

$$
V_1-V_+ +V_1-V_2+V_1-V_3=0,
$$

$$
3V_1-V_2-V_3=V_+.
$$

For $V_2$,

$$
\frac{V_2-V_+}{R}
+\frac{V_2-V_1}{R}
+\frac{V_2-V_3}{R}
+\frac{V_2-V_4}{R}=0.
$$

$$
-V_1+4V_2-V_3-V_4=V_+.
$$

For the middle junctions, using the same process, it will give us

$$
-V_{i-2}-V_{i-1}+4V_i-V_{i+1}-V_{i+2}=0.
$$

For $V_{N-1}$,

$$
-V_{N-3}-V_{N-2}+4V_{N-1}-V_N=V_-=0.
$$

Lastly, for $V_N$,

$$
-V_{N-2}-V_{N-1}+3V_N=V_-=0.
$$

Hence, these are the equations satisfied by $V_1,\ldots,V_N$.

In [33]:
# Matrix A
A = np.array([
    [ 3., -1., -1.,  0.,  0.,  0.],
    [-1.,  4., -1., -1.,  0.,  0.],
    [-1., -1.,  4., -1., -1.,  0.],
    [ 0., -1., -1.,  4., -1., -1.],
    [ 0.,  0., -1., -1.,  4., -1.],
    [ 0.,  0.,  0., -1., -1.,  3.]
])

# VEctor w
w = np.array([5., 5., 0., 0., 0., 0.])

print(A)
print(w)

[[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]]
[5. 5. 0. 0. 0. 0.]


In [34]:
# Finding Voltages
print(np.linalg.solve(A, w))

[3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


In [41]:
# Banded matrix solver adapted from M. Newman, Computational Physics, 2nd edition. 

from numpy import copy

def banded(Aa, va, up, down):

    # Copy the inputs and determine the size of the system
    A = copy(Aa)
    v = copy(va)
    N = len(v)

    # Gaussian elimination
    for m in range(N):

        # Normalization factor
        div = A[up,m]

        # Update the vector first
        v[m] /= div
        for k in range(1,down+1):
            if m+k<N:
                v[m+k] -= A[up+k,m]*v[m]

        # Now normalize the pivot row of A and subtract from lower ones
        for i in range(up):
            j = m + up - i
            if j<N:
                A[i,j] /= div
                for k in range(1,down+1):
                    A[i+k,j] -= A[up+k,m]*A[i,j]

    # Backsubstitution
    for m in range(N-2,-1,-1):
        for i in range(up):
            j = m + up - i
            if j<N:
                v[m] -= A[i,j]*v[j]

    return v

# Number of internal junctions
N = 10000

# Banded matrix
A = np.zeros((5, N))

# Main diagonal
A[2, :] = 4
A[2, 0] = 3
A[2, -1] = 3

# First upper and lower diagonals
A[1, 1:] = -1
A[3, :-1] = -1

# Second upper and lower diagonals
A[0, 2:] = -1
A[4, :-2] = -1

# Vector w
w = np.zeros(N)
w[0] = 5
w[1] = 5

# Solve
v = banded(A, w, 2, 2)

print(v)

[4.99888228e+00 4.99861842e+00 4.99802841e+00 ... 1.97158611e-03
 1.38158071e-03 1.11772227e-03]


#### Problem 1 code summary

The code finds the voltages in the resistor chain for $N = 10000$ junctions. The matrix is stored only using its five nonzero diagonals in otder to save memory, and then the system is solved using a banded Gaussian-elimination method.

###### Reference:

Newman, M. (2025). Computational physics (2nd ed.). https://websites.umich.edu/~mejn/computational-physics/.

### Problem 2 (Statics)


Solve the following matrix problems. Set-up the linear equations that describe the problem then solve them 

Part 1: Suppose you have a hanging mass M supported by two ropes (angled by $\alpha$ and $\beta$ with respect to the ceiling). Make a function that calculates the tension on each of the ropes. Put your function in a python file and call it here in the notebook. Check that the answer by computer matches your own computations.

<del>
Part 2: 
Masses $m_1, m_2, m_3$, and $m_4$ lie on a $2.00$ [m] beam of negligible mass. They are located $0.20, 0.70, 1.10$, and $1.40$ [m] away from the left end of the beam. Determine the masses $m_1, m_2, m_3$, and $m_4$, given the following constraints: 

- The total mass is $8.00$ [kg]
- If a pivot is placed halfway, the beam will balance if a $1.05$ [kg] mass is placed on the right-end of the beam
- If a pivot is placed $1.20$ [m] away from the right end, then the beam would balance if a $550$ [g] mass is placed on the left end of the beam.
- If the system is split midway, the total mass on the left is $1.00$ [kg] heavier than the total mass on the right
</del>

In [31]:
from math import sin, cos, radians, pi

def TensionCalculator(alpha, beta, M):

    # constant
    g = 9.81

    # Convert to radians
    alpha = radians(alpha)
    beta = radians(beta)

    # Coefficient Matrix
    u = np.array([[sin(alpha), sin(beta)], 
                  [-cos(alpha), cos(beta)]
                 ])
    # RHS Vector
    y = np.array([M*g, 0])

    # Calculation
    tensions = np.linalg.solve(u, y)

    return tensions

In [32]:
# Trial
print(TensionCalculator(45, 45, 10))

[69.36717523 69.36717523]


#### Problem 2 code summary

The code finds the tension of the two ropes by using the forces acting on the mass. I set up the equations in a matrix and used `np.linalg.solve()` to find the tensions.

## Section 3 (Notes)

### Some codes for solving matrix problems

* solving matrix equations ($\bf{A}\vec{x} = \vec{b}$) -> `np.linalg.solve`
* LU-decomposition ($\bf{A} = \bf{L}\bf{U}$) -> `scipy.linalg.lu`
* matrix inversion ($\bf{A}^{-1}$) -> `np.linalg.inv`
* QR-decomposition ($\bf{A} = \bf{Q}\bf{R}$) -> `scipy.linalg.qr`
* eigenvalue problem ($\bf{A}\vec{x} = \lambda \vec{x}$) -> `np.linalg.eig`

Solving matrix problems by themselves isn't difficult. There is an abundance of linear algebra libraries that are ready to use: from the battle-tested ones (the classic [BLAS](https://www.netlib.org/blas/) and [LAPACK](https://www.netlib.org/lapack/)), HPC tools for large problems ([ScaLAPACK](https://netlib.org/scalapack/)), to hardware-accelerated ones often with GPUs ([cuBLAS](https://docs.nvidia.com/cuda/cublas/index.html) and [cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html) for NVIDIA). 

The hardest part is actually composing the matrix. How do you transform a physical problem into a linear algebra problem?

* Circuit: https://personal.math.vt.edu/embree/cmda3606/chapter2.pdf
* Embree [main notes](https://personal.math.vt.edu/embree/cmda3606notes.pdf) + [lab manual](https://personal.math.vt.edu/embree/labman.pdf)

#### Sample Usage (Testing different codes)

In [2]:
A = np.array([[1,0,2],[-2,-1,3],[0,3,5]])
B = np.array([[-2],[1],[-3]])


In [3]:
sigma_z = [[1,0],[0,-1]]
sigma_y = [[0,-1j],[1j,0]]
sigma_x = [[0,1],[1,0]]

In [4]:
ans = np.linalg.solve(sigma_x, sigma_y)
ans = np.linalg.inv(A) @ B


In [5]:
from scipy.linalg import *
p, l, u = lu(A)
p, l, u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.        ,  1.        ,  0.        ],
        [-0.5       , -0.16666667,  1.        ]]),
 array([[-2.        , -1.        ,  3.        ],
        [ 0.        ,  3.        ,  5.        ],
        [ 0.        ,  0.        ,  4.33333333]]))

### Importing functions from a python file

In [6]:
import samplePackage as sP

In [9]:
testMat = sP.createZerosArray(4,5)

In [13]:
testMat[1] = [1,2,3,4,5]

In [14]:
testMat

array([[0., 0., 0., 0., 0.],
       [1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.roll

In [19]:
## Useful tips. Not required to solve the problems below!

# Suppose you have a Numpy array
x = np.zeros((4,4))
x[1,2] = 5
for row in x:
    print(row)

#rint(x[0,1:3])


# I can move all values to the left/right using roll
x_roll = np.roll(x, 1) # change 1 to -1, what happens? 
#x_roll2 = np.roll(x, -1)
print(x_roll)

x_roll2 = np.roll(x, 2)
print(x_roll2)

[0. 0. 0. 0.]
[0. 0. 5. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]]


**End of exercise.**